name: Deploy Angular App to EC2

on:
  push:
    branches:
      - main
    paths:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --prod

      - name: Copy SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/deploy_key
          chmod 600 /tmp/deploy_key

      - name: Create target directory on EC2
        run: |
          ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} << 'EOF'
            mkdir -p /home/${EC2_USER}/angular-app/
          EOF
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: Copy built files to EC2
        run: |
          scp -i /tmp/deploy_key -o StrictHostKeyChecking=no -r dist/ ${EC2_USER}@${EC2_HOST}:/home/ubuntu/angular-app/
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: Deploy on EC2
        run: |
          ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} << 'EOF'
            cd /home/ubuntu/angular-app/
            if ! command -v npm &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            if ! command -v ng &> /dev/null; then
              sudo npm install -g @angular/cli
            fi
            nohup ng serve --host 0.0.0.0 --port 4200 > /tmp/ng-serve.log 2>&1 &
            echo "Angular application is deployed and running."
          EOF
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: Clean up
        run: rm -f /tmp/deploy_key
