name: Deploy Angular App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Build Angular Application
      run: npm run build --prod

    - name: Save SSH Private Key
      run: |
        echo "$EC2_SSH_KEY" > /tmp/deploy_key
        chmod 600 /tmp/deploy_key

    - name: Debugging Information
      run: |
        echo "EC2_HOST=${{ secrets.EC2_HOST }}"
        echo "EC2_USER=${{ secrets.EC2_USER }}"

    - name: Test SSH Connection
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no -o ConnectTimeout=10 $EC2_USER@$EC2_HOST "echo Connection successful"
      
    - name: Deploy to EC2
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}  # Your private key for SSH
      run: |
        # Ensure directory exists on EC2
        ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} << 'EOF'
        mkdir -p /home/${EC2_USER}/angular-app
        EOF

        # Copy files to EC2 instance
        scp -i /tmp/deploy_key -o StrictHostKeyChecking=no -r dist/ ${EC2_USER}@${EC2_HOST}:/home/${EC2_USER}/angular-app/

        # SSH into EC2 instance and deploy the application
        ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} << 'EOF'
        cd /home/${EC2_USER}/angular-app
        # Install Node.js and Angular CLI if not already installed
        curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
        sudo apt-get install -y nodejs
        sudo npm install -g @angular/cli
        
        # Install http-server if not installed
        sudo npm install -g http-server

        # Serve the Angular app on port 4200
        http-server dist/ -p 4200
        EOF
