name: Deploy Angular App to EC2

on:
  push:
    branches:
      - main
    paths:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --prod

      - name: Copy SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/deploy_key
          chmod 600 /tmp/deploy_key

      - name: Copy built files to EC2
        run: |
          ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} 'mkdir -p /home/ubuntu/angular-app'
          scp -i /tmp/deploy_key -o StrictHostKeyChecking=no -r dist/ ubutnu@${EC2_HOST}:/home/ubuntu/angular-app/
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: Deploy on EC2
        run: |
          ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} << 'EOF'
            cd /home/ubuntu/angular-app/
            if ! command -v http-server &> /dev/null; then
              sudo npm install -g http-server
            fi
            # Serve the application using http-server
            nohup http-server dist/ -p 4200 > /tmp/angular-app.log 2>&1 &
            echo "Angular application is deployed and running."
          EOF
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: Clean up
        run: rm -f /tmp/deploy_key
