name: Deploy to EC2

on:
  push:
    branches:
      - main  # or any branch you want to trigger the deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Switch to root user
          sudo su
          # Navigate to your project directory
          cd /path/to/your/angular/project

          # Pull the latest code
          git pull origin main

          # Install dependencies and build
          npm install
          ng build
          ng serve
          # Optional: Restart the application or server
          # You might need to set up a service manager like PM2 for this
        EOF
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
